### ISSUE TITLE
Have an Ability to Change Name and Icon

### ISSUE THREAD

**Issue by Valpuia** [MarJose123/filament-lockscreen#23]
Can we change the title translation for "Lock Screen" inside Filament User Menu.. and also ICON

**Edited**

I can change all these using [https://filamentphp.com/docs/2.x/admin/navigation#customizing-the-user-menu](https://filamentphp.com/docs/2.x/admin/navigation#customizing-the-user-menu) and register inside `lockscreen` array key. But there can be easy way to achieve this because `lockscreen` is already registered in `userMenuItems`. Just provide translation key for `title/lable` and icon name in `config`

**Comment by MarJose123** [comment]
Hi @Valpuia I believe this need to be done on the package (this) itself to have an ability to change the icon and its name.

Feel free to PR!

**Comment by MarJose123** [comment]
Please see the PR for your self to update and setup your requirement.

**Comment by Valpuia** [comment]
Hi @MarJose123 this PR is already close, so I don't want to create another issue for the possible same bug..

Can you also make the `Password` field translateable also..
It will be very good for all end user (my preferences)

**Comment by MarJose123** [comment]
> Hi @MarJose123 this PR is already close, so I don't want to create another issue for the possible same bug..
> 
> Can you also make the `Password` field translateable also.. It will be very good for all end user (my preferences)

Just add the "Password" as your key, and add your value to reflect on your system. 

```php
return [
   'Password' => // your language to the password to be use.
    'heading' => 'Lock Screen',
    'user_menu_title' => 'Lock Screen',
    'button' => [
        'switch_account' => 'Switch Account',
        'submit_label' => 'Sign In'
//    ...
```

**Comment by Valpuia** [comment]
Yes, If i create `en.json` file and added the key `"Password":"Password abc"` then it's working.. but some people like me handle translation file from `lang\eng\admin.php` and having another `lang\en.json` just for this seems a bad idea...

Sorry for bad english.

**Comment by MarJose123** [comment]
> Yes, If i create `en.json` file and added the key `"Password":"Password abc"` then it's working.. but some people like me handle translation file from `lang\en\admin.php` and having another `lang\en.json` just for this seems a bad idea...
> 
> Sorry for bad english.

I'm happy for your PR, I will add translation to the password fields, once I'm free.

**Comment by Valpuia** [comment]
#26 submitted PR
