### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by SkeyPunyapal** [MarJose123/filament-lockscreen#4]
after login in again it is redirecting to the home page rather it should be redirected to the admin panel.

**Comment by MarJose123** [comment]
> after login in again it is redirecting to the home page rather it should be redirected to the admin panel.

you need to update your `home_url` in your filament config to redirect to your admin panel, or possible you have the default web route of laravel that you need to change.

**Comment by SkeyPunyapal** [comment]
> > after login in again it is redirecting to the home page rather it should be redirected to the admin panel.
> 
> you need to update your `home_url` in your filament config to redirect to your admin panel, or possible you have the default web route of laravel that you need to change.

I know that but if I'll change that then normal users will also redirect to the admin panel so that will be not a good practice, if possible can you give an option in config for redirecting the URL? or getting back to the same URL from where it was locked?

**Comment by MarJose123** [comment]
> 



> > > after login in again it is redirecting to the home page rather it should be redirected to the admin panel.
> > 
> > 
> > you need to update your `home_url` in your filament config to redirect to your admin panel, or possible you have the default web route of laravel that you need to change.
> 
> I know that but if I'll change that then normal users will also redirect to the admin panel so that will be not a good practice, if possible can you give an option in config for redirecting the URL? or getting back to the same URL from where it was locked?

I'm happy to approved a PR if you are interested.

**Comment by MarJose123** [comment]
I will be working on it 🤠
