### ISSUE TITLE
lock screen opens `admin/screen/lock` but doesn't lock

### ISSUE THREAD

**Issue by Saifallak** [MarJose123/filament-lockscreen#44]
```
 ->authMiddleware([
                Authenticate::class,
                Locker::class,
            ])
```

```
->plugins([
     
                Lockscreen::make(),
              
            ]);
```

clicking on the lock screen from user-menu

redirects me to `admin/screen/lock`

but shows the dashboard normally.

![image](https://github.com/MarJose123/filament-lockscreen/assets/6053156/a050f353-1c26-429b-a818-5c0c3281d537)

**Comment by MarJose123** [comment]
Follow the instructions from the README.
```
use lockscreen\FilamentLockscreen\Lockscreen;
use lockscreen\FilamentLockscreen\Http\Middleware\Locker;

public function panel(Panel $panel): Panel
{
    return $panel
        // ...
        ->plugin(new Lockscreen());  // <- Add this
         ->authMiddleware([
                // ...
                 Locker::class, // <- Add this
            ]);
}
```

**Comment by Saifallak** [comment]
i did, you can see that in OP. thats copy from what i added @MarJose123

**Comment by MarJose123** [comment]
Hi @Saifallak you used `Lockscreen::make()` which is the Lockscreen doens't use that instead use the `new Lockscreen()` under the plugin call method.

**Comment by hcaz** [comment]
Its a shame this plugin is not using the started method as it may not be the only plugin installed, fornatily you can do the following:
```php
->plugins([
    new Lockscreen,
    ...
]);
```
