### ISSUE TITLE
Infinite Redirect to /screen/lock

### ISSUE THREAD

**Issue by MrLinkwolf** [MarJose123/filament-lockscreen#68]
The goal was to implement a lock screen feature in a Laravel/Filament application, redirecting users to a lock screen page after a period of inactivity. However, a problem arose: even when the user was already on the lock screen page, the system continued redirecting them there, causing an endless loop.

Testing was conducted on the following versions:

Laravel: _laravel/framework version ^11.9_
Filament: _filament/filament version ^3.2_

**Initial Code:**
The initial code checked if the request method was GET and if the lockscreen session variable was set. If both conditions were true, it redirected to the lock screen page. However, it did not account for cases where the user was already on this page, resulting in an unnecessary redirection loop.

```
public function handle($request, Closure $next)
{
    if (
        $request->method() === 'GET' &&
        $request->session()->get('lockscreen')
    ) {
        $panelId = filament()->getCurrentPanel()?->getId();
        return redirect()->route("lockscreen.{$panelId}.page");
    }

    return $next($request);
}
```

**Problem:**
This approach caused an endless redirection loop because the code didn’t check if the user was already on the lock screen page.

**Solution:**
The solution was to add a condition to check if the current URL matches the lock screen URL. If the user is already on the lock screen page, the middleware skips the redirection. To achieve this, we used _config('filament-lockscreen.url')_ and compared it with the current path.

```
public function handle($request, Closure $next)
{
    if (
        $request->method() === 'GET' &&
        $request->session()->get('lockscreen') &&
        '/' . $request->path() !== config('filament-lockscreen.url')
    ) {
        $panelId = filament()->getCurrentPanel()?->getId();
        return redirect()->route("lockscreen.{$panelId}.page");
    }

    return $next($request);
}
```

![image](https://github.com/user-attachments/assets/cb1a650f-a1e3-4230-a41a-1de1581deb46)

**Comment by MarJose123** [comment]
Hi, thank you for reporting this issue. My actual plan with the package was to lock the page for all requests as long as it was still locked, or the session has still "lockscreen.".

If I'm correct, you are using `MarJose123/filament-lockscreen: "v2.3"`.

Based on the issue you encountered, you are calling the old route that is using the GET method for locking the application, and the logic you implemented seems to be forcing the app to route to the lockscreen page. 

There are some changes made that are possible to make a cause in your application in `v2.3` released.

You need to call this route `route("lockscreen.{$panel->getId()}.lock-session"))` via the POST method to be able to fix the infinite call of the GET route of the lockscreen page.
