### ISSUE TITLE
Mount is called twice

### ISSUE THREAD

**Issue by galliroberto** [MarJose123/filament-lockscreen#70]
Mount is called twice.
The first time as http request, the second one as livewire update

![image](https://github.com/user-attachments/assets/d05f7a26-7eba-4df2-9e8f-2ec505b7fd34)

**Comment by galliroberto** [comment]
Sorry, I didn't see a field that update a property on-init

**Comment by MarJose123** [comment]
I'm not sure, but I think the first call of mount is expected behavior, and the second, I believe, is a default behavior of livewire for refreshing its component.

**Comment by galliroberto** [comment]
Yes, sorry man, I put js fingerprint, when it is calculated, the component refresh.

**Comment by MarJose123** [comment]
no worries. I will close the ticket now.
